boxes:
  1:
    world: world
    x: 100
    y: 64
    z: 100
    respawn_seconds: 300
    loot:
      - material: DIAMOND
        amount: 1
        chance: 50
      - material: GOLD_INGOT
        amount: 3
        chance: 100
messages:
  prefix: "&6[СолдИнБокс]&r "
  box_restored: "&aЛутбокс №{id} восстановлен!"
  box_created: "&aСоздан новый лутбокс №{id}."
  box_reset_all: "&eВсе лутбоксы сброшены."
  box_reset_one: "&eЛутбокс №{id} сброшен."
  reload: "&aКонфиг перезагружен."
  not_found: "&cЛутбокс не найден."
  not_ready: "&cЭтот лутбокс ещё на перезарядке."
  editor_title: "Редактор лута: #{id}"
  open_title: "Лутбокс #{id}"
  click_too_fast: "&cСлишком быстро кликаете по предметам!"
