boxes:
  - world: world
    x: 100
    y: 64
    z: 100
  - world: world
    x: 120
    y: 64
    z: 120
messages:
  box_respawned: "&aLoot box respawned!"
  all_boxes_respawned: "&aAll loot boxes respawned!"
