settings:
  click_cooldown_ms: 200
  default_respawn_seconds: 300

messages:
  prefix: "&6[СолдИнБокс]&r "
  box_restored: "&aЛутбокс №{id} восстановлен!"
  box_created: "&aСоздан новый лутбокс №{id}."
  box_reset_all: "&eВсе лутбоксы сброшены."
  box_reset_one: "&eЛутбокс №{id} сброшен."
  reload: "&aКонфиг перезагружен."
  not_found: "&cЛутбокс не найден."
  not_ready: "&cЭтот лутбокс ещё на перезарядке."
  editor_title: "Редактор лута: #{id}"
  open_title: "Лутбокс #{id}"
  click_too_fast: "&cСлишком быстро кликаете по предметам!"
