name: SoldInBox
main: dev.soldinbox.SoldInBox
version: 1.0.0
api-version: 1.16
author: You
commands:
  soldinbox:
    description: SoldInBox admin commands
    usage: /<command> <reload|reset|resetbox|setbox|edit>
    aliases: [sib, sinb]
permissions:
  soldinbox.admin:
    description: Allows admin commands
    default: op
