name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B -e -V -DskipTests package
      - name: Archive plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: SoldInBox
          path: target/SoldInBox-*.jar
